name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install capacitor
        run: npm install -g @capacitor/cli @capacitor/core

      - name: Setup capacitor config file
        run: npx cap init --appName 'angular-mobile-app' --appId 'com.example.app' --webDir 'dist/angular-mobile-app'

      - name: Add native iOS and Android packages
        run: npm install -g @capacitor/android @capacitor/ios

      - name: Add Android
        run: npx cap add android

      - name: Add iOS
        run: npx cap add ios

      - name: Build app and copy build folder to the ios/android projects
        run: rm -rf node_modules && pnpm install && pnpm run build && npx cap sync

      # - name: Build Android Debug APK
      #   run: cd android && ./gradlew assembleDebug

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: apk/app-debug.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: apk/app.aab
