name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Install capacitor
        run: npm install -g @capacitor/cli @capacitor/core

      - name: Install app dependencies
        run: npm install

      - name: Setup capacitor config file
        run: rm capacitor.config.ts && npx cap init 'angular-mobile-app' 'com.example.app' --web-dir 'dist/angular-mobile-app'

      - name: Add native iOS and Android packages
        run: npm install -g @capacitor/android @capacitor/ios

      - name: Add Android
        run: npx cap add android

      - name: Add iOS
        run: npx cap add ios

      - name: List folders
        run: ls -la

      - name: Build app and copy build folder to the ios/android projects
        run: rm -rf node_modules && pnpm install && pnpm run build && npx cap sync

      # - name: Build Android Debug APK
      #   run: cd android && ./gradlew assembleDebug

      - name: Go into android folder
        run: cd android && ls -la && cd ..

      - name: Generate the Android App Bundle
        run: cd android && ./gradlew bundle && cd ..

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: apk/app-debug.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: apk/app.aab
